#!/usr/bin/perl

# This is a simple obfuscation test.
# It's also not maintained.

             use                             strict;                                   use                                  warnings;                                   use                                                   File::Path                                              'rmtree';
             my                             ($_a,$_b);
             if                                 (                                    $ARGV[0]                                   &&                                    $ARGV[0]                                                    eq                                                 "\x2d\x76"                                )                                   {                              die            "looper  v1.3.2\n";  }
            elsif                               (                                    $ARGV[0]                                   &&                                    $ARGV[0]                                                    =~                                                /\x2d\x68$/i                               )                                   {                              die
    "\x4c\x6f\x6f\x70\x73          \x7a\x69\x70\x70\x69\x6e\x67                    \x61\x6e\x64                \x75\x6e\x7a\x69\x70\x70\x69\x6e\x67                   \x6f\x66                   \x66\x6f\x6c\x64\x65\x72\x73\x2f\x61\x72\x63\x68\x69\x76\x65\x73\x2e
  \x55\x73\x61\x67\x65\x3a     \x6c\x6f\x6f\x70\x65\x72\x2e\x70\x6c            \x5b\x66\x69\x6c\x65                   \x2e\x2e\x2e\x5d\n";}
             if                                 (                                    $ARGV[0]                                   )                                        {                                                       $_a                                                      =                        "\x2e\x2f\x5f$ARGV[0]";$_b                      =                    "\x2e\x2f\x2e$ARGV[0]";     }
            else                                {                                      $_a                                      =                    "\x2e\x2f\x5f\x6c\x6f\x6f\x70\x65\x72";$_b                                   =                                    "\x2e\x2f\x2e\x6c\x6f\x6f\x70\x65\x72";                 }
             if                                (-d                                     $_a)                                     {                                  `\x74\x61\x72                                           \x2d\x7a\x63\x66                                              $_b                                 $_a`;                            rmtree($_a);                       print
"\x50\x72\x6f\x63\x65\x73\x73            \x46\x2d\x3e\x41            \x63\x6f\x6d\x70\x6c\x65\x74\x65\x2e\n";                   }
            elsif                              (-e                                     $_b)                                     {                                  `\x74\x61\x72                                           \x2d\x78\x7a\x66                                             $_b`;                             unlink($_b);                           print
"\x50\x72\x6f\x63\x65\x73\x73            \x41\x2d\x3e\x46            \x63\x6f\x6d\x70\x6c\x65\x74\x65\x2e\n";                   }
            else                                {                                  mkdir($_a);                                print                          "\x46\x6f\x6c\x64\x65\x72                               \x64\x6f\x65\x73\x6e\x27\x74                             \x65\x78\x69\x73\x74\x21          \x43\x72\x65\x61\x74\x69\x6e\x67  \x65\x6d\x70\x74\x79\x2e\x2e\x2e\n";             }

# Copyright © 2018 - Judah Caruso Rodriguez (0px.moe)